--------------------------------------------------------
--  File created - «·√Õœ-‰Ì”«‰-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "AYA"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(5,0), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AYA.PRODUCTS
SET DEFINE OFF;
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (1,'Toys',1351);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (2,'Toys',874);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (3,'Toys',1686);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (4,'Clothes',1453);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (5,'Perfumes',1215);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (6,'Toys',972);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (7,'Perfumes',1097);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (8,'Perfumes',62);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (9,'Perfumes',1666);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (10,'Sports',1298);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (11,'Sports',668);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (12,'Home Appliances',1540);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (13,'Books',1694);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (14,'Toys',177);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (15,'Electronics',346);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (16,'Perfumes',1620);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (17,'Perfumes',960);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (18,'Clothes',1969);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (19,'Perfumes',1186);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (20,'Home Appliances',34);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (21,'Clothes',179);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (22,'Electronics',1308);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (23,'Perfumes',1448);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (24,'Clothes',863);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (25,'Toys',1473);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (26,'Toys',139);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (27,'Home Appliances',1439);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (28,'Sports',1825);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (29,'Electronics',1279);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (30,'Books',1648);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (31,'Toys',1847);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (32,'Books',74);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (33,'Clothes',805);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (34,'Home Appliances',372);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (35,'Clothes',286);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (36,'Clothes',421);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (37,'Sports',635);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (38,'Home Appliances',1110);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (39,'Perfumes',339);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (40,'Home Appliances',1808);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (41,'Toys',1574);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (42,'Home Appliances',1957);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (43,'Electronics',1673);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (44,'Books',1464);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (45,'Perfumes',124);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (46,'Books',427);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (47,'Electronics',1276);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (48,'Toys',58);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (49,'Toys',312);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (50,'Toys',1594);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (51,'Toys',536);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (52,'Toys',747);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (53,'Sports',182);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (54,'Sports',637);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (55,'Home Appliances',207);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (56,'Toys',73);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (57,'Sports',1017);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (58,'Home Appliances',794);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (59,'Electronics',421);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (60,'Sports',1314);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (61,'Books',475);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (62,'Electronics',1038);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (63,'Toys',1806);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (64,'Sports',1624);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (65,'Books',1432);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (66,'Toys',1701);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (67,'Electronics',1630);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (68,'Perfumes',1695);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (69,'Toys',567);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (70,'Toys',1508);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (71,'Books',334);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (72,'Electronics',40);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (73,'Books',1876);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (74,'Perfumes',36);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (75,'Clothes',493);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (76,'Sports',118);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (77,'Electronics',187);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (78,'Clothes',716);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (79,'Clothes',440);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (80,'Sports',174);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (81,'Toys',734);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (82,'Books',1689);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (83,'Books',352);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (84,'Books',77);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (85,'Books',1017);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (86,'Sports',205);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (87,'Sports',1636);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (88,'Books',1404);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (89,'Sports',522);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (90,'Sports',418);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (91,'Home Appliances',72);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (92,'Sports',1180);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (93,'Books',1949);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (94,'Clothes',594);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (95,'Perfumes',1238);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (96,'Toys',998);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (97,'Home Appliances',1701);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (98,'Sports',956);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (99,'Clothes',1462);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (100,'Books',1333);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (101,'Sports',662);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (102,'Home Appliances',953);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (103,'Toys',1531);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (104,'Toys',1025);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (105,'Books',1046);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (106,'Sports',831);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (107,'Clothes',235);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (108,'Perfumes',804);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (109,'Books',217);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (110,'Perfumes',90);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (111,'Toys',173);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (112,'Home Appliances',1592);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (113,'Books',1373);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (114,'Electronics',229);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (115,'Sports',1237);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (116,'Toys',491);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (117,'Clothes',1956);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (118,'Perfumes',1778);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (119,'Sports',1079);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (120,'Electronics',924);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (121,'Books',1810);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (122,'Toys',532);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (123,'Clothes',614);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (124,'Toys',1344);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (125,'Books',1601);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (126,'Electronics',1929);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (127,'Sports',1787);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (128,'Electronics',1276);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (129,'Home Appliances',1485);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (130,'Perfumes',1570);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (131,'Books',1769);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (132,'Clothes',1631);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (133,'Toys',695);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (134,'Perfumes',635);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (135,'Clothes',1158);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (136,'Electronics',1786);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (137,'Electronics',1637);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (138,'Sports',1066);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (139,'Perfumes',1516);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (140,'Books',44);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (141,'Clothes',1722);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (142,'Toys',1518);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (143,'Toys',1009);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (144,'Sports',1048);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (145,'Toys',1020);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (146,'Books',566);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (147,'Perfumes',380);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (148,'Perfumes',1506);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (149,'Electronics',20);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (150,'Perfumes',337);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (151,'Perfumes',1000);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (152,'Electronics',673);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (153,'Clothes',1120);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (154,'Electronics',1195);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (155,'Perfumes',178);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (156,'Perfumes',1183);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (157,'Sports',1289);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (158,'Perfumes',235);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (159,'Home Appliances',21);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (160,'Home Appliances',124);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (161,'Electronics',1153);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (162,'Books',1765);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (163,'Sports',1189);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (164,'Home Appliances',1497);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (165,'Sports',848);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (166,'Books',924);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (167,'Home Appliances',903);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (168,'Books',376);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (169,'Sports',669);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (170,'Books',1104);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (171,'Perfumes',808);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (172,'Toys',1289);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (173,'Home Appliances',1167);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (174,'Perfumes',1623);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (175,'Sports',1924);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (176,'Home Appliances',1485);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (177,'Toys',1624);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (178,'Home Appliances',988);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (179,'Clothes',771);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (180,'Toys',1492);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (181,'Toys',913);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (182,'Home Appliances',386);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (183,'Toys',1130);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (184,'Toys',850);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (185,'Home Appliances',42);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (186,'Sports',1100);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (187,'Sports',1054);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (188,'Sports',44);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (189,'Books',1770);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (190,'Home Appliances',887);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (191,'Books',1352);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (192,'Electronics',1860);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (193,'Toys',1246);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (194,'Sports',1256);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (195,'Electronics',956);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (196,'Books',1213);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (197,'Home Appliances',1953);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (198,'Electronics',922);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (199,'Sports',1123);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (200,'Books',413);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (201,'Clothes',1441);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (202,'Perfumes',1410);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (203,'Clothes',252);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (204,'Electronics',443);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (205,'Books',675);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (206,'Electronics',631);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (207,'Toys',279);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (208,'Books',1400);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (209,'Home Appliances',1463);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (210,'Electronics',918);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (211,'Home Appliances',1622);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (212,'Sports',1024);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (213,'Perfumes',867);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (214,'Sports',1822);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (215,'Electronics',1805);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (216,'Clothes',257);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (217,'Clothes',1870);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (218,'Books',565);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (219,'Toys',68);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (220,'Electronics',896);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (221,'Perfumes',117);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (222,'Perfumes',1193);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (223,'Sports',1969);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (224,'Home Appliances',1905);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (225,'Clothes',154);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (226,'Home Appliances',995);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (227,'Books',1097);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (228,'Home Appliances',1394);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (229,'Clothes',1573);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (230,'Toys',1936);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (231,'Toys',475);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (232,'Perfumes',243);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (233,'Toys',1441);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (234,'Clothes',1298);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (235,'Perfumes',1749);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (236,'Perfumes',537);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (237,'Books',1262);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (238,'Sports',1829);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (239,'Books',1458);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (240,'Books',311);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (241,'Sports',1829);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (242,'Books',387);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (243,'Toys',1640);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (244,'Sports',876);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (245,'Clothes',841);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (246,'Perfumes',935);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (247,'Perfumes',814);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (248,'Electronics',1300);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (249,'Clothes',283);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (250,'Home Appliances',1181);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (251,'Clothes',881);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (252,'Sports',1946);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (253,'Electronics',1337);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (254,'Electronics',1047);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (255,'Clothes',615);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (256,'Home Appliances',719);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (257,'Home Appliances',927);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (258,'Books',449);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (259,'Perfumes',55);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (260,'Clothes',500);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (261,'Home Appliances',1402);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (262,'Electronics',1006);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (263,'Perfumes',814);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (264,'Perfumes',503);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (265,'Sports',693);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (266,'Home Appliances',806);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (267,'Clothes',974);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (268,'Home Appliances',775);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (269,'Perfumes',74);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (270,'Electronics',547);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (271,'Books',1026);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (272,'Clothes',1952);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (273,'Electronics',825);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (274,'Books',845);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (275,'Clothes',233);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (276,'Sports',1044);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (277,'Books',1184);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (278,'Home Appliances',797);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (279,'Books',655);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (280,'Perfumes',1338);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (281,'Perfumes',573);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (282,'Home Appliances',339);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (283,'Books',1506);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (284,'Home Appliances',1545);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (285,'Books',217);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (286,'Electronics',1548);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (287,'Electronics',1430);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (288,'Sports',728);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (289,'Toys',840);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (290,'Perfumes',1798);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (291,'Home Appliances',1414);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (292,'Sports',228);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (293,'Home Appliances',196);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (294,'Electronics',1559);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (295,'Sports',1563);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (296,'Electronics',1315);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (297,'Home Appliances',1741);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (298,'Toys',356);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (299,'Electronics',1022);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (300,'Toys',1168);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (301,'Toys',1251);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (302,'Home Appliances',225);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (303,'Home Appliances',1951);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (304,'Books',1941);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (305,'Books',1905);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (306,'Clothes',1917);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (307,'Books',661);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (308,'Home Appliances',1994);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (309,'Sports',1822);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (310,'Perfumes',1651);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (311,'Electronics',827);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (312,'Perfumes',951);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (313,'Clothes',745);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (314,'Clothes',1390);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (315,'Books',1540);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (316,'Clothes',1194);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (317,'Clothes',1279);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (318,'Home Appliances',27);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (319,'Toys',1325);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (320,'Home Appliances',1879);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (321,'Clothes',117);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (322,'Clothes',296);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (323,'Books',564);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (324,'Perfumes',649);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (325,'Books',903);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (326,'Sports',221);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (327,'Perfumes',1546);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (328,'Perfumes',1263);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (329,'Clothes',673);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (330,'Home Appliances',1609);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (331,'Books',1051);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (332,'Home Appliances',885);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (333,'Books',973);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (334,'Electronics',876);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (335,'Perfumes',516);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (336,'Home Appliances',244);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (337,'Clothes',721);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (338,'Perfumes',1241);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (339,'Home Appliances',254);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (340,'Sports',1765);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (341,'Toys',257);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (342,'Electronics',141);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (343,'Electronics',1504);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (344,'Books',343);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (345,'Electronics',553);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (346,'Sports',37);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (347,'Toys',1816);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (348,'Home Appliances',442);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (349,'Electronics',1312);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (350,'Sports',1130);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (351,'Sports',976);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (352,'Books',187);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (353,'Electronics',1599);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (354,'Clothes',1435);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (355,'Home Appliances',596);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (356,'Sports',1046);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (357,'Home Appliances',801);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (358,'Home Appliances',383);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (359,'Perfumes',313);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (360,'Home Appliances',688);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (361,'Home Appliances',624);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (362,'Sports',420);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (363,'Electronics',826);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (364,'Toys',797);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (365,'Toys',1364);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (366,'Sports',735);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (367,'Sports',847);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (368,'Toys',303);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (369,'Home Appliances',1585);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (370,'Clothes',580);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (371,'Perfumes',359);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (372,'Perfumes',437);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (373,'Clothes',1040);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (374,'Toys',958);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (375,'Home Appliances',334);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (376,'Home Appliances',167);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (377,'Books',920);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (378,'Books',1367);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (379,'Toys',1984);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (380,'Perfumes',500);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (381,'Perfumes',175);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (382,'Home Appliances',1375);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (383,'Home Appliances',161);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (384,'Books',1839);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (385,'Sports',829);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (386,'Clothes',1063);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (387,'Books',828);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (388,'Perfumes',901);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (389,'Sports',46);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (390,'Perfumes',208);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (391,'Sports',95);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (392,'Perfumes',1008);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (393,'Perfumes',1820);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (394,'Electronics',462);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (395,'Perfumes',1073);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (396,'Toys',1666);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (397,'Clothes',1666);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (398,'Clothes',1229);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (399,'Electronics',54);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (400,'Toys',834);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (401,'Toys',1728);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (402,'Books',187);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (403,'Clothes',1328);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (404,'Sports',1627);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (405,'Perfumes',1392);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (406,'Home Appliances',170);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (407,'Sports',1934);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (408,'Toys',288);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (409,'Books',231);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (410,'Perfumes',711);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (411,'Books',1311);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (412,'Home Appliances',392);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (413,'Books',1879);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (414,'Electronics',1561);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (415,'Sports',1550);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (416,'Perfumes',1507);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (417,'Electronics',517);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (418,'Perfumes',1307);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (419,'Toys',392);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (420,'Electronics',1241);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (421,'Clothes',1825);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (422,'Books',1065);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (423,'Toys',917);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (424,'Clothes',1313);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (425,'Books',1926);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (426,'Electronics',271);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (427,'Electronics',1888);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (428,'Home Appliances',37);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (429,'Books',749);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (430,'Home Appliances',1367);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (431,'Toys',102);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (432,'Electronics',1785);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (433,'Home Appliances',1524);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (434,'Books',1263);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (435,'Electronics',1195);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (436,'Perfumes',1749);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (437,'Toys',149);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (438,'Clothes',542);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (439,'Clothes',756);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (440,'Electronics',1906);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (441,'Electronics',94);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (442,'Perfumes',537);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (443,'Sports',683);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (444,'Sports',1615);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (445,'Perfumes',219);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (446,'Clothes',1125);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (447,'Sports',1529);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (448,'Sports',815);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (449,'Home Appliances',1064);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (450,'Electronics',1482);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (451,'Toys',365);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (452,'Sports',858);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (453,'Sports',1347);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (454,'Sports',756);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (455,'Sports',1006);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (456,'Home Appliances',552);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (457,'Clothes',1143);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (458,'Sports',24);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (459,'Electronics',806);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (460,'Perfumes',1609);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (461,'Sports',1548);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (462,'Sports',1736);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (463,'Clothes',134);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (464,'Toys',1926);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (465,'Electronics',1948);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (466,'Home Appliances',1543);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (467,'Electronics',1635);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (468,'Clothes',881);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (469,'Perfumes',110);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (470,'Electronics',49);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (471,'Sports',1781);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (472,'Sports',768);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (473,'Home Appliances',1178);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (474,'Books',779);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (475,'Toys',528);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (476,'Toys',936);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (477,'Clothes',1641);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (478,'Toys',1158);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (479,'Clothes',1609);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (480,'Home Appliances',568);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (481,'Perfumes',306);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (482,'Sports',481);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (483,'Perfumes',563);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (484,'Sports',532);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (485,'Sports',685);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (486,'Electronics',397);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (487,'Home Appliances',313);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (488,'Electronics',560);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (489,'Sports',818);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (490,'Clothes',879);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (491,'Electronics',595);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (492,'Perfumes',1919);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (493,'Perfumes',300);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (494,'Books',693);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (495,'Books',1111);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (496,'Electronics',674);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (497,'Books',1944);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (498,'Home Appliances',783);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (499,'Perfumes',1704);
Insert into AYA.PRODUCTS (PRODUCT_ID,CATEGORY,PRICE) values (500,'Electronics',1351);
--------------------------------------------------------
--  DDL for Index PK_PRODUCTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYA"."PK_PRODUCTS" ON "AYA"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "AYA"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "AYA"."PRODUCTS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "AYA"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "AYA"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
