--------------------------------------------------------
--  File created - «·√Õœ-‰Ì”«‰-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "AYA"."USERS" 
   (	"USER_ID" NUMBER(5,0), 
	"AGE" NUMBER(3,0), 
	"COUNTRY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AYA.USERS
SET DEFINE OFF;
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (763,45,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (764,47,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (765,45,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (766,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (767,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (768,41,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (769,32,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (770,25,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (771,39,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (772,18,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (773,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (774,25,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (775,29,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (776,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (777,44,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (778,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (779,35,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (780,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (781,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (782,65,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (783,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (784,52,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (785,65,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (786,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (787,30,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (788,23,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (789,53,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (790,50,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (791,64,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (792,53,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (793,43,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (794,38,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (795,51,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (796,64,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (797,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (798,62,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (799,26,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (800,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (801,38,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (802,59,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (803,24,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (804,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (805,55,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (806,26,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (807,36,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (808,22,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (809,33,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (810,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (811,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (812,53,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (813,46,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (814,43,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (815,51,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (816,23,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (817,60,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (818,48,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (819,55,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (820,37,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (821,45,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (822,22,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (823,33,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (824,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (825,23,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (826,22,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (827,17,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (828,55,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (829,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (830,39,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (831,28,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (832,59,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (833,21,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (834,64,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (835,16,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (836,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (837,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (838,40,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (839,27,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (840,23,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (841,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (842,60,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (843,46,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (844,42,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (845,40,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (846,44,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (847,64,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (848,19,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (849,49,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (850,65,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (851,47,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (852,32,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (853,62,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (854,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (855,50,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (856,45,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (857,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (858,50,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (859,32,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (860,42,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (861,52,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (862,51,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (863,50,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (864,36,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (865,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (866,57,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (867,40,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (868,18,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (869,46,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (870,26,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (871,34,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (872,18,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (873,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (874,29,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (875,29,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (876,41,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (877,40,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (878,30,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (879,27,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (880,18,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (881,38,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (882,32,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (883,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (884,49,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (885,33,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (886,26,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (887,27,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (888,58,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (889,50,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (890,35,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (891,19,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (892,62,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (893,63,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (894,64,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (895,42,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (896,24,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (897,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (898,45,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (899,25,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (900,28,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (901,17,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (902,64,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (903,33,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (904,38,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (905,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (906,65,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (907,37,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (908,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (909,43,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (910,39,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (911,21,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (912,50,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (913,42,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (914,62,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (915,56,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (916,36,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (917,17,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (918,39,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (919,57,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (920,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (921,20,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (922,55,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (923,40,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (924,18,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (925,42,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (926,54,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (927,41,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (928,24,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (929,29,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (930,63,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (931,21,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (932,38,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (933,46,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (934,49,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (935,25,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (936,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (937,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (938,23,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (939,52,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (940,37,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (941,34,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (942,56,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (943,40,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (944,31,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (945,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (946,38,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (947,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (948,63,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (949,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (950,23,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (951,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (952,56,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (953,54,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (954,55,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (955,62,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (956,44,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (957,63,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (958,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (959,24,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (960,33,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (961,62,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (962,58,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (963,26,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (964,61,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (965,21,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (966,25,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (967,24,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (968,65,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (969,62,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (970,36,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (971,41,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (972,62,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (973,59,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (974,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (975,18,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (976,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (977,58,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (978,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (979,26,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (980,61,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (981,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (982,48,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (983,36,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (984,29,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (985,35,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (986,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (987,47,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (988,27,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (989,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (990,47,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (991,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (992,24,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (993,43,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (994,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (995,22,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (996,25,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (997,44,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (998,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (999,58,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (1000,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (1,35,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (2,36,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (3,40,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (4,39,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (5,51,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (6,35,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (7,22,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (8,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (9,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (10,54,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (11,44,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (12,26,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (13,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (14,44,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (15,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (16,30,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (17,40,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (18,49,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (19,36,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (20,53,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (21,40,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (22,30,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (23,50,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (24,63,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (25,53,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (26,18,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (27,51,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (28,42,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (29,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (30,24,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (31,43,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (32,65,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (33,41,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (34,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (35,33,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (36,25,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (37,56,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (38,29,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (39,47,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (40,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (41,54,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (42,42,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (43,34,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (44,56,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (45,57,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (46,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (47,25,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (48,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (49,55,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (50,49,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (51,23,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (52,24,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (53,39,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (54,47,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (55,19,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (56,50,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (57,40,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (58,54,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (59,21,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (60,24,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (61,38,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (62,23,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (63,64,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (64,20,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (65,63,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (66,50,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (67,47,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (68,18,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (69,61,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (70,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (71,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (72,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (73,53,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (74,62,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (75,58,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (76,27,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (77,52,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (78,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (79,54,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (80,29,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (81,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (82,21,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (83,54,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (84,40,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (85,31,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (86,64,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (87,47,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (88,50,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (89,28,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (90,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (91,64,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (92,42,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (93,53,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (94,23,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (95,63,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (96,52,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (97,63,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (98,35,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (99,52,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (100,37,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (101,46,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (102,20,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (103,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (104,61,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (105,40,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (106,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (107,56,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (108,57,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (109,24,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (110,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (111,64,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (112,62,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (113,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (114,18,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (115,42,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (116,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (117,45,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (118,62,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (119,26,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (120,33,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (121,58,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (122,44,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (123,33,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (124,44,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (125,32,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (126,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (127,45,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (128,65,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (129,18,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (130,36,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (131,62,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (132,18,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (133,23,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (134,19,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (135,39,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (136,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (137,22,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (138,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (139,27,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (140,42,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (141,26,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (142,46,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (143,46,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (144,58,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (145,22,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (146,43,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (147,54,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (148,37,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (149,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (150,61,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (151,18,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (152,37,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (153,40,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (154,56,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (155,63,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (156,18,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (157,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (158,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (159,60,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (160,62,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (161,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (162,62,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (163,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (164,49,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (165,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (166,54,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (167,19,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (168,46,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (169,22,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (170,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (171,16,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (172,54,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (173,64,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (174,39,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (175,38,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (176,23,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (177,20,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (178,38,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (179,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (180,65,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (181,50,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (182,36,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (183,27,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (184,49,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (185,16,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (186,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (187,49,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (188,41,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (189,45,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (190,48,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (191,41,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (192,31,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (193,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (194,31,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (195,57,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (196,44,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (197,28,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (198,55,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (199,38,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (200,47,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (201,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (202,48,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (203,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (204,40,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (205,47,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (206,48,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (207,61,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (208,41,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (209,56,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (210,63,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (211,50,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (212,28,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (213,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (214,52,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (215,32,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (216,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (217,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (218,62,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (219,45,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (220,37,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (221,27,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (222,50,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (223,21,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (224,20,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (225,42,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (226,19,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (227,64,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (228,20,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (229,26,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (230,56,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (231,58,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (232,42,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (233,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (234,17,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (235,29,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (236,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (237,18,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (238,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (239,44,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (240,53,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (241,31,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (242,28,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (243,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (244,52,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (245,65,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (246,55,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (247,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (248,22,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (249,34,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (250,52,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (251,60,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (252,42,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (253,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (254,45,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (255,51,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (256,19,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (257,34,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (258,65,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (259,28,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (260,44,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (261,19,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (262,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (263,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (264,52,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (265,55,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (266,55,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (267,20,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (268,54,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (269,55,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (270,24,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (271,62,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (272,43,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (273,53,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (274,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (275,21,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (276,25,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (277,47,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (278,42,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (279,55,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (280,21,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (281,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (282,37,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (283,40,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (284,35,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (285,52,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (286,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (287,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (288,41,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (289,38,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (290,56,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (291,36,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (292,39,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (293,56,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (294,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (295,33,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (296,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (297,57,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (298,41,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (299,45,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (300,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (301,19,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (302,47,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (303,27,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (304,59,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (305,17,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (306,45,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (307,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (308,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (309,20,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (310,58,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (311,30,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (312,54,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (313,36,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (314,64,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (315,44,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (316,58,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (317,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (318,22,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (319,52,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (320,19,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (321,42,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (322,20,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (323,63,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (324,49,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (325,34,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (326,40,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (327,64,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (328,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (329,53,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (330,21,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (331,62,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (332,36,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (333,53,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (334,64,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (335,38,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (336,22,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (337,21,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (338,52,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (339,30,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (340,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (341,55,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (342,23,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (343,30,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (344,60,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (345,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (346,24,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (347,22,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (348,39,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (349,57,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (350,58,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (351,26,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (352,34,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (353,57,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (354,57,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (355,16,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (356,60,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (357,56,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (358,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (359,38,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (360,25,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (361,36,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (362,22,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (363,47,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (364,63,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (365,49,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (366,45,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (367,19,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (368,26,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (369,58,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (370,21,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (371,57,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (372,29,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (373,33,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (374,46,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (375,47,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (376,56,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (377,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (378,40,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (379,61,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (380,62,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (381,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (382,65,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (383,22,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (384,44,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (385,50,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (386,53,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (387,50,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (388,44,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (389,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (390,29,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (391,47,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (392,38,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (393,41,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (394,36,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (395,65,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (396,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (397,50,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (398,62,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (399,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (400,28,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (401,53,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (402,19,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (403,49,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (404,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (405,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (406,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (407,46,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (408,16,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (409,47,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (410,44,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (411,57,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (412,65,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (413,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (414,61,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (415,47,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (416,52,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (417,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (418,39,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (419,61,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (420,60,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (421,59,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (422,42,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (423,40,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (424,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (425,63,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (426,59,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (427,23,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (428,41,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (429,19,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (430,60,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (431,54,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (432,31,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (433,53,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (434,22,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (435,47,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (436,60,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (437,55,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (438,19,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (439,22,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (440,50,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (441,30,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (442,30,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (443,52,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (444,60,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (445,19,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (446,16,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (447,20,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (448,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (449,22,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (450,27,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (451,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (452,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (453,54,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (454,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (455,30,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (456,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (457,47,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (458,37,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (459,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (460,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (461,61,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (462,45,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (463,57,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (464,36,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (465,42,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (466,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (467,65,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (468,58,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (469,49,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (470,44,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (471,25,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (472,50,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (473,37,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (474,63,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (475,29,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (476,46,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (477,37,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (478,47,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (479,31,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (480,33,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (481,55,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (482,45,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (483,59,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (484,51,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (485,37,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (486,50,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (487,28,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (488,25,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (489,19,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (490,34,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (491,26,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (492,48,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (493,54,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (494,46,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (495,33,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (496,38,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (497,22,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (498,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (499,47,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (500,62,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (501,40,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (502,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (503,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (504,22,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (505,63,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (506,26,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (507,54,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (508,33,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (509,64,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (510,37,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (511,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (512,30,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (513,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (514,60,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (515,45,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (516,60,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (517,30,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (518,55,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (519,63,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (520,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (521,57,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (522,17,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (523,62,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (524,47,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (525,60,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (526,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (527,39,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (528,55,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (529,34,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (530,28,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (531,56,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (532,23,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (533,55,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (534,58,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (535,47,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (536,21,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (537,18,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (538,54,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (539,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (540,54,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (541,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (542,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (543,29,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (544,51,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (545,27,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (546,27,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (547,49,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (548,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (549,43,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (550,58,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (551,38,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (552,45,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (553,36,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (554,47,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (555,44,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (556,41,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (557,49,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (558,21,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (559,28,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (560,50,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (561,25,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (562,34,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (563,59,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (564,20,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (565,44,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (566,57,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (567,38,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (568,23,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (569,42,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (570,23,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (571,40,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (572,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (573,64,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (574,61,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (575,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (576,45,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (577,16,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (578,62,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (579,46,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (580,21,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (581,32,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (582,52,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (583,17,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (584,58,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (585,23,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (586,45,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (587,65,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (588,24,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (589,54,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (590,46,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (591,61,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (592,60,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (593,44,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (594,16,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (595,17,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (596,60,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (597,26,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (598,32,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (599,42,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (600,37,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (601,57,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (602,53,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (603,56,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (604,63,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (605,21,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (606,25,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (607,30,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (608,22,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (609,63,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (610,63,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (611,55,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (612,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (613,27,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (614,42,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (615,48,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (616,18,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (617,28,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (618,29,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (619,35,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (620,19,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (621,31,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (622,31,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (623,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (624,19,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (625,42,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (626,33,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (627,34,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (628,53,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (629,54,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (630,41,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (631,52,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (632,19,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (633,35,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (634,45,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (635,45,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (636,35,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (637,46,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (638,46,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (639,57,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (640,35,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (641,24,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (642,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (643,61,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (644,25,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (645,49,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (646,38,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (647,17,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (648,55,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (649,57,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (650,34,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (651,40,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (652,32,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (653,55,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (654,37,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (655,51,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (656,38,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (657,48,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (658,25,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (659,50,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (660,21,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (661,55,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (662,35,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (663,57,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (664,29,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (665,31,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (666,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (667,63,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (668,32,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (669,63,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (670,31,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (671,29,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (672,49,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (673,50,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (674,40,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (675,43,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (676,46,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (677,22,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (678,45,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (679,52,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (680,18,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (681,43,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (682,60,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (683,30,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (684,54,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (685,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (686,36,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (687,26,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (688,61,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (689,28,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (690,23,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (691,43,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (692,57,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (693,35,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (694,53,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (695,28,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (696,65,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (697,53,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (698,53,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (699,36,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (700,53,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (701,45,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (702,39,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (703,27,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (704,43,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (705,60,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (706,17,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (707,32,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (708,30,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (709,29,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (710,41,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (711,36,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (712,59,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (713,43,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (714,59,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (715,26,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (716,22,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (717,28,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (718,57,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (719,56,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (720,57,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (721,54,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (722,57,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (723,55,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (724,65,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (725,45,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (726,35,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (727,63,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (728,58,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (729,47,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (730,24,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (731,26,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (732,19,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (733,49,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (734,51,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (735,34,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (736,28,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (737,53,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (738,33,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (739,19,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (740,46,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (741,20,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (742,54,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (743,21,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (744,44,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (745,27,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (746,48,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (747,58,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (748,31,'Qatar');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (749,42,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (750,21,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (751,60,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (752,63,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (753,52,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (754,30,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (755,54,'Kuwait');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (756,32,'Egypt');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (757,18,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (758,26,'Morocco');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (759,16,'Saudi Arabia');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (760,57,'Jordan');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (761,42,'UAE');
Insert into AYA.USERS (USER_ID,AGE,COUNTRY) values (762,38,'UAE');
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYA"."PK_USERS" ON "AYA"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "AYA"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "AYA"."USERS" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "AYA"."USERS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "AYA"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
